<html>
<head>
<title>electives System</title>
</head>
<body>
<h3>welcome to electives class system!</h3>
<table border="1" cellspacing='0'>
<tr bgcolor='gray'><td>课程号</td><td>课程名称</td><td>课程老师</td><td>课程学分</td><td>我要点评</td></tr>
<?php foreach ($this->classes as $classes) { ?>
<tr>
<td><?=$classes['id']?></td>
<td><?=$classes['name']?></td>
<td><?=$classes['teacher']?></td>
<td><?=$classes['score']?></td>
<td><a href="/index/showcommentui?classid=<?=$classes['id']?>">点评</a></td>
</tr>
<?php }?>
</table>
</body>
<div><div><a href="/login/loginui">登陆</a><a href="/login/registerui">注册</a></div></div>
</html>