<html>
<head>
<title>Management System</title>
</head>
<body>
<h3></h3>
<form action="/admin/addclass" method="post">
id:<input type="text" name=class_id id=class_id  "><br/>
name<input type="text" name=class_name id=class_name><br/>
teacher<input type="text" name=class_teacher id=class_teacher><br/>
score:<input type="text" name=class_score id=class_score><br/>
<input type="submit" value='add'>
</form>
</body>
</html>
